'use strict';

const jwt = require('jsonwebtoken');
const { User, Tenant } = require('../models');
const { jwt: jwtConfig } = require('../config/env');
const { ROLES } = require('../config/constants');
const logger = require('../utils/logger');

/**
 * Auth Service — all business logic for authentication lives here.
 */

const signToken = (payload) =>
  jwt.sign(payload, jwtConfig.secret, { expiresIn: jwtConfig.expiresIn });

// ─────────────────────────────────────────────────────────────────────────────
// register — Creates a new Tenant + first Admin user.
// ─────────────────────────────────────────────────────────────────────────────
const register = async ({ name, email, password, tenantName }) => {
  const existing = await User.findOne({ email: email.toLowerCase().trim() });
  if (existing) {
    const err = new Error('An account with this email already exists');
    err.status = 409;
    throw err;
  }

  const baseSlug = tenantName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

  let slug = baseSlug;
  const slugExists = await Tenant.findOne({ slug });
  if (slugExists) {
    slug = `${baseSlug}-${Math.random().toString(36).slice(2, 6)}`;
  }

  // inviteCode is auto-generated by Tenant model default
  const tenant = await Tenant.create({ name: tenantName.trim(), slug });

  const passwordHash = await User.hashPassword(password);
  const user = await User.create({
    name: name.trim(),
    email: email.toLowerCase().trim(),
    passwordHash,
    role: ROLES.ADMIN, // first user is always admin
    tenantId: tenant._id,
  });

  const token = signToken({
    userId: user._id,
    tenantId: tenant._id,
    role: user.role,
  });

  logger.info(`New tenant registered: ${tenant.slug} | user: ${user.email}`);

  return { token, user, tenant };
};

// ─────────────────────────────────────────────────────────────────────────────
// joinTenant — Allows a new user to join an existing org using an invite code.
// The first user to use an invite auto-gets Viewer role.
// Admin can later promote them from the Admin panel.
// ─────────────────────────────────────────────────────────────────────────────
const joinTenant = async ({ name, email, password, inviteCode }) => {
  // 1. Find the tenant by invite code
  const tenant = await Tenant.findOne({ inviteCode: inviteCode.trim() });
  if (!tenant) {
    const err = new Error('Invalid invite code. Please check the link and try again.');
    err.status = 400;
    throw err;
  }

  // 2. Email must be globally unique
  const existing = await User.findOne({ email: email.toLowerCase().trim() });
  if (existing) {
    const err = new Error('An account with this email already exists. Try logging in.');
    err.status = 409;
    throw err;
  }

  // 3. Create new user in the tenant as VIEWER (Admin grants higher roles)
  const passwordHash = await User.hashPassword(password);
  const user = await User.create({
    name: name.trim(),
    email: email.toLowerCase().trim(),
    passwordHash,
    role: ROLES.VIEWER, // always starts as viewer
    tenantId: tenant._id,
  });

  const token = signToken({
    userId: user._id,
    tenantId: tenant._id,
    role: user.role,
  });

  logger.info(`User joined tenant "${tenant.slug}" via invite: ${user.email}`);

  return { token, user, tenant };
};

// ─────────────────────────────────────────────────────────────────────────────
// getInviteInfo — Returns tenant name for a given invite code (for the join form preview).
// ─────────────────────────────────────────────────────────────────────────────
const getInviteInfo = async (code) => {
  const tenant = await Tenant.findOne({ inviteCode: code.trim() }, 'name slug');
  if (!tenant) {
    const err = new Error('Invite code not found or has expired.');
    err.status = 404;
    throw err;
  }
  return { tenantName: tenant.name, tenantSlug: tenant.slug };
};

// ─────────────────────────────────────────────────────────────────────────────
// login
// ─────────────────────────────────────────────────────────────────────────────
const login = async ({ email, password }) => {
  const user = await User.findOne({ email: email.toLowerCase().trim() })
    .select('+passwordHash')
    .populate('tenantId', 'name slug inviteCode');

  if (!user || !user.isActive) {
    const err = new Error('Invalid email or password');
    err.status = 401;
    throw err;
  }

  const isMatch = await user.comparePassword(password);
  if (!isMatch) {
    const err = new Error('Invalid email or password');
    err.status = 401;
    throw err;
  }

  const token = signToken({
    userId: user._id,
    tenantId: user.tenantId._id,
    role: user.role,
  });

  logger.info(`User logged in: ${user.email}`);
  return { token, user };
};

// ─────────────────────────────────────────────────────────────────────────────
// getMe
// ─────────────────────────────────────────────────────────────────────────────
const getMe = async (userId) => {
  const user = await User.findById(userId).populate('tenantId', 'name slug inviteCode');
  if (!user || !user.isActive) {
    const err = new Error('User not found');
    err.status = 404;
    throw err;
  }
  return user;
};

module.exports = { register, joinTenant, login, getMe, getInviteInfo };
